### PR TITLE
Account for AWS Lambda function states to prevent errors when updating configuration + code

### PR DESCRIPTION
**Pull request by patrick-dignifi**
per https://docs.aws.amazon.com/lambda/latest/dg/functions-states.html
AWS Lambda now prevents the updating of the configuration or code of a lambda while the Lambda is in a pending state.
Updating the configuration puts the lambda in a pending state, thus guaranteeing an error if the user of this action is trying to update both configuration and code at the same time.

Proposed solution:
adding a wait in between updating function configuration and function code if configuration is being updated

### CODE REVIEW

**Review by rafistrauss — APPROVED** [review]

**Comment by rafistrauss** [comment]
@appleboy any chance we can get this merged & built to unblock https://github.com/appleboy/lambda-action/issues/46?

**Comment by patrick-dignifi** [comment]
full disclosure, I'm no GO expert, so there might be a better way to accomplish this change. I just would love to see this change added to support AWS Lambdas better

**Comment by rafistrauss** [comment]
@patrick-dignifi Same 😁

**Comment by sunsheeppoplar** [comment]
bumping this for visibility!

**Comment by mikkixlisa** [comment]
@appleboy Any updates on this?

**Comment by appleboy** [comment]
I will take it.

**Pull request closed without merging**
