### PR TITLE
Fix binary included in image

### PR DESCRIPTION
**Pull request by mavimo**

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by mavimo** [comment]
@appleboy I have a question, why do you replace drone plugin base image with alpine? Plugin base image already include certificates... (I'm asking since I used your plugin as scaffold for mine 📦 )

https://github.com/appleboy/drone-lambda/commit/3f389cc4cb5f7fd7be0f7e678341a06e15bbb709#diff-3254677a7917c6c01f55212f86c57fbfL1

**Comment by appleboy** [comment]
@mavimo because of support zip file into to `/tmp` folder.

**Comment by mavimo** [comment]
@appleboy ok, so I should go back to original base image since I create zip on memory instead of writing it on disk, thanks!

**Comment by appleboy** [comment]
@mavimo yes, you are right.

**Pull request merged**
